language: php
php:
  - '7.1'
  - '7.2'
  
sudo: false

env:
  - APP_DEBUG=false

install:
  - composer install --prefer-dist --optmize-autoloader --quiet

script: 
  - phpunit -c phpunit.xml --coverage-text
